### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 110-115: character maps to <undefined>

### ISSUE THREAD

**Issue by deadcombo** [GjjvdBurg/signal2html#2]
Hello, I'm getting this error.

```
PS C:\Users\win>  signal2html -i C:\Users\win\Desktop\Backups\Signal\RAWBAK -o C:\Users\win\Desktop\Backups\Signal\signal_html
c:\users\win\appdata\local\programs\python\python38-32\lib\site-packages\signal2html\core.py:42: UserWarning: Warning: Found untested Signal database version: 20.
  warnings.warn(
Traceback (most recent call last):
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\win\AppData\Local\Programs\Python\Python38-32\Scripts\signal2html.exe\__main__.py", line 7, in <module>
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\site-packages\signal2html\__main__.py", line 8, in main
    sys.exit(realmain())
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\site-packages\signal2html\ui.py", line 33, in main
    process_backup(args.input_dir, args.output_dir)
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\site-packages\signal2html\core.py", line 213, in process_backup
    dump_thread(t, output_dir)
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\site-packages\signal2html\html.py", line 186, in dump_thread
    fp.write(html)
  File "c:\users\win\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 110-115: character maps to <undefined>
```

Running on Windows 10. Thank you for taking the time here, looks quite nice.

**Comment by GjjvdBurg** [comment]
Hi @deadcombo, thanks for letting me know about this. I've never tested the program on a Windows machine so it's quite possible that's a factor. I've just pushed a potential fix to the [bugfix/encoding](https://github.com/GjjvdBurg/signal2html/tree/bugfix/encoding) branch. If you know how to install a package from GitHub it would be great if you can try it out to see if that solves the problem.

**Comment by GjjvdBurg** [comment]
Thanks for letting me know that the first problem was solved, I'll update the package when we have this one sorted out too. Just to clarify what's going on here, could it be the case that this message quotes someone who is not in your contacts or in your signal threads? 

I've created a new branch [bugfix/quote_author](https://github.com/GjjvdBurg/signal2html/tree/bugfix/quote_author) with an attempt to solve this problem. I can't easily test it here, so hopefully you can check if this works.

**Comment by deadcombo** [comment]
` Just to clarify what's going on here, could it be the case that this message quotes someone who is not in your contacts or in your signal threads?`

Well, that was a text from myself, so it's probably something like that. I can't check because signal2html hasn't gotten to it yet, have a new bug:

```
signal2html.exe -i "C:\Users\win\Desktop\Backups\Signal\RAWBAK" -o "C:\Users\win\Desktop\Backups\Signal\signal_html"
C:\Users\win\AppData\Local\Programs\Python\Python38-32\lib\site-packages\signal2html-0.1.0-py3.8.egg\signal2html\core.py:42: UserWarning: Warning: Found untested Signal database version: 20.
Traceback (most recent call last):
  File "C:\Users\win\AppData\Local\Programs\Python\Python38-32\Scripts\signal2html-script.py", line 11, in <module>
    load_entry_point('signal2html==0.1.0', 'console_scripts', 'signal2html')()
  File "C:\Users\win\AppData\Local\Programs\Python\Python38-32\lib\site-packages\signal2html-0.1.0-py3.8.egg\signal2html\__main__.py", line 8, in main
  File "C:\Users\win\AppData\Local\Programs\Python\Python38-32\lib\site-packages\signal2html-0.1.0-py3.8.egg\signal2html\ui.py", line 33, in main
  File "C:\Users\win\AppData\Local\Programs\Python\Python38-32\lib\site-packages\signal2html-0.1.0-py3.8.egg\signal2html\core.py", line 204, in process_backup
sqlite3.OperationalError: no such table: thread
```

I'm able to replicate it in WSL.

Thanks for the support.

**Comment by GjjvdBurg** [comment]
Huh, that's strange, that line (204) is called before the previous error with the quoted message. So it worked before but now doesn't anymore. Is the database file corrupt perhaps? You can try opening the ``.sqlite`` file in a program such as [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser) or [dbeaver](https://dbeaver.io/) to check if it has a ``thread`` table.

**Comment by deadcombo** [comment]
Hmm, I just extracted the backup again and it works again. I think it got to all my messages, at least the ones I cared.

However, I've no attachments in the threads:
`
C:\Users\win\AppData\Local\Programs\Python\Python38-32\lib\site-packages\signal2html-0.1.0-py3.8.egg\signal2html\core.py:107: UserWarning: Warning: couldn't find attachment C:\Users\win\Desktop\Backups\Signal\RAWBAK\Attachment_239_1548886157063.bin!`

Sure enough, attachment 239 is missing. (Maybe it's something I deleted?)
Anyway, no attachments load at all.

**Comment by GjjvdBurg** [comment]
Glad it works again. Yes, with missing attachments a warning will be generated and this generally corresponds to deleted attachments.

I'm not quite sure why the attachments don't load though. It *might* have to do with the way local files are loaded. Currently the path to the attachments is simply embedded in the HTML. What you could try is to edit the generated HTML file and add the text ``file://`` before the attachment path (so it would read ``file://C:/Users/win/Desktop/Backups/Signal/RAWBAK/Attachment_....`` (note the change from `\` to `/` as well). If that solves it I could implement that change in the package.

**Comment by GjjvdBurg** [comment]
Closing due to inactivity, please reopen the issue if the problem persists.
