### ISSUE TITLE
Troubleshooting signal2html execution

### ISSUE THREAD

**Issue by shamwow27** [GjjvdBurg/signal2html#30]
Having trouble processing the signal_backup to signal_html. I apologize if this is user error but I figured it might be a bug? Any help is appreciated. I have my signal_backup/ and signal_html/ directories within my Python39/ directory. Executing the signalbackup-tools_win.exe and creating a decrypted backup seemed to have went perfect, beforehand. 

```
PS C:\Users\Chris\AppData\Local\Programs\Python\Python39>
PS C:\Users\Chris\AppData\Local\Programs\Python\Python39> ./python.exe -m signal2html -i signal_backup/ -o signal_html/
INFO:signal2html.versioninfo:Using database version 105.
WARNING:signal2html.core:Found untested Signal database version: 105.
WARNING:signal2html.addressbook:Recipient with rid 2 not in addressbook, adding it.
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\site-packages\signal2html\__main__.py", line 20, in <module>
    main()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\site-packages\signal2html\__main__.py", line 15, in main
    sys.exit(realmain())
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\site-packages\signal2html\ui.py", line 35, in main
    process_backup(args.input_dir, args.output_dir)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\site-packages\signal2html\core.py", line 348, in process_backup
    recipient = addressbook.get_recipient_by_address(recipient_id)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\site-packages\signal2html\addressbook.py", line 232, in get_recipient_by_address
    return self._add_recipient(rid, "", get_random_color(), False, "")
TypeError: _add_recipient() missing 1 required positional argument: 'phone'
PS C:\Users\Chris\AppData\Local\Programs\Python\Python39>
```

**Comment by egecelikci** [comment]
I am also facing the same error. I hope the logs help.
```shell
$ signal2html -i signal_backup/ -o signal_html/
Found untested Signal database version: 105.
Recipient with rid 1 not in addressbook, adding it.
Traceback (most recent call last):
  File "/home/egecelikci/.local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/egecelikci/.local/lib/python3.9/site-packages/signal2html/__main__.py", line 15, in main
    sys.exit(realmain())
  File "/home/egecelikci/.local/lib/python3.9/site-packages/signal2html/ui.py", line 35, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/egecelikci/.local/lib/python3.9/site-packages/signal2html/core.py", line 348, in process_backup
    recipient = addressbook.get_recipient_by_address(recipient_id)
  File "/home/egecelikci/.local/lib/python3.9/site-packages/signal2html/addressbook.py", line 232, in get_recipient_by_address
    return self._add_recipient(rid, "", get_random_color(), False, "")
TypeError: _add_recipient() missing 1 required positional argument: 'phone'
```

**Comment by GjjvdBurg** [comment]
@ericthegrey do you have a chance to look at this? It seems to occur in the new addressbook class. The trivial fix is probably easy but as it is in a part of the code that is "not expected to happen" I'm not sure if there is more going on. If you don't have time I can try to take a stab at it of course.

**Comment by ChemoCosmo** [comment]
Not sure if related but the process fails with my current Backup (Database-Version 102) as well:
```
Traceback (most recent call last):
  File "/home/chemo/.local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/chemo/.local/lib/python3.8/site-packages/signal2html/__main__.py", line 15, in main
    sys.exit(realmain())
  File "/home/chemo/.local/lib/python3.8/site-packages/signal2html/ui.py", line 35, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/chemo/.local/lib/python3.8/site-packages/signal2html/core.py", line 357, in process_backup
    dump_thread(t, output_dir)
  File "/home/chemo/.local/lib/python3.8/site-packages/signal2html/html.py", line 124, in dump_thread
    COLORMAP[clr],
KeyError: 'C210'
```
Worked with a (much) older one.

**Comment by GjjvdBurg** [comment]
@ChemoCosmo thanks for letting me know. Judging from the traceback your problem is different than the others (see #31).

**Comment by ericthegrey** [comment]
> @ericthegrey do you have a chance to look at this? It seems to occur in the new addressbook class. The trivial fix is probably easy but as it is in a part of the code that is "not expected to happen" I'm not sure if there is more going on. If you don't have time I can try to take a stab at it of course.

Hi @GjjvdBurg I think the "obvious fix" is needed anyway, but I'm also surprised to see this. Perhaps something there is something different causing this in newer database versions. I will try a new backup over the week-end and check whether I can reproduce.

**Comment by shamwow27** [comment]
Thanks for your help.

**Comment by GjjvdBurg** [comment]
> Hi @GjjvdBurg I think the "obvious fix" is needed anyway, but I'm also surprised to see this. Perhaps there is something different causing this in newer database versions. I will try a new backup over the week-end and check whether I can reproduce.

Thanks @ericthegrey, much appreciated!

**Comment by ericthegrey** [comment]
Unfortunately my backup didn't have any issue, so we're left with the simple code fix, scheduled for the next release. Hopefully this solves the immediate problem for the people affected. I would appreciate any hint why the affected thread has no contact data (you should see it as `#1` in the listing (where '1' is the ID from the message `Recipient with rid 1 not in addressbook, adding it.`).

**Comment by shamwow27** [comment]
> 
> 
> Unfortunately my backup didn't have any issue, so we're left with the simple code fix, scheduled for the next release. Hopefully this solves the immediate problem for the people affected. I would appreciate any hint why the affected thread has no contact data (you should see it as `#1` in the listing (where '1' is the ID from the message `Recipient with rid 1 not in addressbook, adding it.`).

Fixed worked for me, thank you!

**Comment by egecelikci** [comment]
reinstalled with `pip install git+https://github.com/GjjvdBurg/signal2html@bugfix/rid_not_found`. the problem is solved for me too, thanks for your help. :pray:

**Comment by GjjvdBurg** [comment]
Great to hear this was fixed, thanks for your help @ericthegrey! As mentioned, if anyone knows why the affected thread has no contact data please let us know. I'll prepare a release to update the package on PyPI right away.
