### ISSUE TITLE
Database version 40 - no such column: profile_joined_name

### ISSUE THREAD

**Issue by Piermaz38** [GjjvdBurg/signal2html#50]
Hi,
I've got a problem to convert an old Signal database version. 

```Found untested Signal database version: 40.
Traceback (most recent call last):
  File "/home/pierre/.local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/__main__.py", line 15, in main
    sys.exit(realmain())
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/ui.py", line 35, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/core.py", line 653, in process_backup
    addressbook = make_addressbook(db, versioninfo)
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/addressbook.py", line 296, in make_addressbook
    return AddressbookV2(db)
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/addressbook.py", line 35, in __init__
    self._load_recipients()  # Must be implemented by subclass
  File "/home/pierre/.local/lib/python3.8/site-packages/signal2html/addressbook.py", line 247, in _load_recipients
    qry = self.db.execute(
sqlite3.OperationalError: no such column: profile_joined_name```

Thanks,

**Comment by GjjvdBurg** [comment]
Hi @Piermaz38, thanks for reporting this error. Unfortunately it seems that supporting the version of the database that you have will require quite some effort. Are you perhaps able to update the Signal version on the phone so that the database will be migrated to a newer version?
