### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'new_members'

### ISSUE THREAD

**Issue by aweinberg38** [GjjvdBurg/signal2html#59]
Many thanks  for 0.2.8 correcting the  attribute 'by'. Unfortunately, there are other issues.
This tile, I get 

signal2html -i db -o out
2021-12-20 13:02:25 | INFO - This is signal2html version 0.2.8
2021-12-20 13:02:25 | INFO - Found Signal database version: 120.
2021-12-20 13:02:25 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "/usr/local/bin/signal2html", line 33, in <module>
    sys.exit(load_entry_point('signal2html==0.2.8', 'console_scripts', 'signal2html')())
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/__main__.py", line 20, in main
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/ui.py", line 35, in main
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/core.py", line 679, in process_backup
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/core.py", line 636, in populate_thread
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/core.py", line 101, in get_sms_records
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/core.py", line 379, in get_data_from_body
  File "/usr/local/lib/python3.9/dist-packages/signal2html-0.2.8-py3.9.egg/signal2html/core.py", line 326, in get_group_update_data_v2
AttributeError: 'NoneType' object has no attribute 'new_members'

**Comment by aweinberg38** [comment]
[signal2html-0.2.8-patch.txt](https://github.com/GjjvdBurg/signal2html/files/7776923/signal2html-0.2.8-patch.txt)

The attached patch solves the issue - at least for me.

**Comment by Tulux** [comment]
I confirm the patch works

**Comment by Gajusbonus** [comment]
I would like to apply the patch,
downloaded signal2html-0.2.8-patch.txt to the directory where signalbackup-tools is

git apply signal2html-0.2.8-patch.txt
error: unrecognized input

? whats wrong?

**Comment by Gajusbonus** [comment]
I installed with pip and I don' t know how to build signal2html  from source.

Or should I patch some file in:
/home/gajus/.local/lib/python3.8/site-packages/signal2html

**Comment by GjjvdBurg** [comment]
Sorry for the slow response on this one, patch is now incorporated in signal2html version 0.2.9. Thanks for providing it @aweinberg38!
