### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'new_members'

### ISSUE THREAD

**Issue by Gajusbonus** [GjjvdBurg/signal2html#64]
Dear GJ,
Thank you so much for this tool. The first db went very well, but another from a different phone has this issue. The reading of db finished without errors, but signal2html ended after 2 minutes with this output:

Traceback (most recent call last):

  File "/home/gajus/.local/bin/signal2html", line 8, in <module>

    sys.exit(main())

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/**main**.py", line 20, in main

    sys.exit(main())

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/ui.py", line 35, in main

    process*backup(args.input*dir, args.output_dir)

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/core.py", line 679, in process_backup

    populate_thread(

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/core.py", line 636, in populate_thread

    sms*records = get*sms_records(db, thread, addressbook)

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/core.py", line 101, in get*sms*records

    data = get*data*from*body(*type, body, addressbook, _id)

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/core.py", line 379, in get*data*from_body

    data = get*group*update*data*v2(

  File "/home/gajus/.local/lib/python3.8/site-packages/signal2html/core.py", line 326, in get*group*update*data*v2

    for member in change.new_members:

AttributeError: 'NoneType' object has no attribute 'new_members'

**Comment by Gajusbonus** [comment]
Sorry, this is a duplicate issue.
Closing it now
