### ISSUE TITLE
Database version 163

### ISSUE THREAD

**Issue by Baptiste-mrch** [GjjvdBurg/signal2html#72]
Hello,
When trying this program, I get this error message:

![image](https://user-images.githubusercontent.com/62337736/205506527-604a8df0-cf7b-4a52-ae69-a9004bbf7d47.png)

Could someone know how to extract my signal backup?

Thanks!

**Comment by CSnowRules** [comment]
The reactions column has been renamed to reaction in the db.

2022-12-04 15:29:16 | INFO - This is signal2html version 0.2.11
2022-12-04 15:29:16 | INFO - Found Signal database version: 163.
2022-12-04 15:29:16 | WARNING - This database version is untested, please report errors.
2022-12-04 15:29:16 | WARNING - Group for recipient 21 is '__textsecure_group__!238da296da5e10924c9709681bef1b9b' which does not exist.
Traceback (most recent call last):
  File ".local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File ".local/lib/python3.10/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File ".local/lib/python3.10/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File ".local/lib/python3.10/site-packages/signal2html/core.py", line 699, in process_backup
    populate_thread(
  File ".local/lib/python3.10/site-packages/signal2html/core.py", line 652, in populate_thread
    mms_records = get_mms_records(
  File ".local/lib/python3.10/site-packages/signal2html/core.py", line 486, in get_mms_records
    qry = db.execute(
sqlite3.OperationalError: no such column: reactions

**Comment by CSnowRules** [comment]
Replace your versioninfo.py and html.py with mine and it should work now. https://github.com/CSnowRules/signal2html-contrib/tree/master/signal2html

**Comment by Baptiste-mrch** [comment]
I have replaced these 2 files in the signal2html folder that pip created, but it doesn't work either :/
![image](https://user-images.githubusercontent.com/62337736/205651640-d4a3af1d-93c7-4f82-80be-ace553f304bc.png)

**Comment by Baptiste-mrch** [comment]
I download all your fork of this repo, and it's works with your repo !!!
Thanks a lot 😄
