### ISSUE TITLE
Database version 166

### ISSUE THREAD

**Issue by DeltaTangoLima** [GjjvdBurg/signal2html#76]
Does anyone have any suggestions as to what I can change to get this working with database version 166? I tried using the updated files from @CSnowRules' fork (found in issue #72), but no luck.

```
2022-12-13 16:08:55 | INFO - This is signal2html version 0.2.11
2022-12-13 16:08:55 | INFO - Found Signal database version: 166.
2022-12-13 16:08:55 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "/Users/dan/Library/Python/3.8/bin/signal2html", line 11, in <module>
    load_entry_point('signal2html==0.2.11', 'console_scripts', 'signal2html')()
  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/signal2html/core.py", line 677, in process_backup
    qry = db.execute("SELECT COUNT(*) FROM sqlite_schema")
sqlite3.OperationalError: no such table: sqlite_schema
```

**Comment by darkest-link** [comment]
I am getting the same error on Signal database version 164.

GjjvdBurg - thank you for the work on this so far, really appreciate it.

**Comment by GVilmos** [comment]
Same error on Signal database version 154 and 170.
