### ISSUE TITLE
Signal database version: 167

### ISSUE THREAD

**Issue by sshaikh** [GjjvdBurg/signal2html#77]
I assume this is just an DB update?

```
2022-12-23 21:06:00 | INFO - This is signal2html version 0.2.11
2022-12-23 21:06:00 | INFO - Found Signal database version: 167.
2022-12-23 21:06:00 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "/home/s/projects/signal/venv/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/s/projects/signal/venv/lib/python3.10/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File "/home/s/projects/signal/venv/lib/python3.10/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/s/projects/signal/venv/lib/python3.10/site-packages/signal2html/core.py", line 688, in process_backup
    query = db.execute(f"SELECT _id, {recipient_id_expr} FROM thread")
sqlite3.OperationalError: no such column: thread_recipient_id
```

**Comment by m477hi45** [comment]
Same problem here:
2023-01-06 09:22:10 | INFO - This is signal2html version 0.2.11
2023-01-06 09:22:10 | INFO - Found Signal database version: 167.
2023-01-06 09:22:10 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "./.local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/m477hi45/.local/lib/python3.8/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File "/home/m477hi45/.local/lib/python3.8/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/m477hi45/.local/lib/python3.8/site-packages/signal2html/core.py", line 677, in process_backup
    qry = db.execute("SELECT COUNT(*) FROM sqlite_schema")
sqlite3.OperationalError: no such table: sqlite_schema


any fix ?

**Comment by sshaikh** [comment]
Seems that there is a PR in progress:  https://github.com/GjjvdBurg/signal2html/pull/78
