### ISSUE TITLE
Signal database version 219: no such table sqlite_schema

### ISSUE THREAD

**Issue by DeltaTangoLima** [GjjvdBurg/signal2html#83]
Getting the below error trying to convert v219 database, but I fear this project is dead. No commits for over a year now...

```
2024-03-22 20:49:45 | INFO - This is signal2html version 0.2.11
2024-03-22 20:49:45 | INFO - Found Signal database version: 219.
2024-03-22 20:49:45 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "/Users/<userid>/Library/Python/3.8/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/Users/<userid>/Library/Python/3.8/lib/python/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File "/Users/<userid>/Library/Python/3.8/lib/python/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File "/Users/<userid>/Library/Python/3.8/lib/python/site-packages/signal2html/core.py", line 677, in process_backup
    qry = db.execute("SELECT COUNT(*) FROM sqlite_schema")
sqlite3.OperationalError: no such table: sqlite_schema
```

**Comment by DeltaTangoLima** [comment]
Just read the README in more detail - switching to signalbackup-tools' `exporthtml` feature instead.
