### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by einstyle** [GjjvdBurg/signal2html#9]
Traceback (most recent call last):
  File "d:\program files\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python36\Scripts\signal2html.exe\__main__.py", line 4, in <module>
  File "d:\program files\python\python36\lib\site-packages\signal2html\__init__.py", line 3, in <module>
    from .core import process_backup
  File "d:\program files\python\python36\lib\site-packages\signal2html\core.py", line 18, in <module>
    from .models import (
  File "d:\program files\python\python36\lib\site-packages\signal2html\models.py", line 15, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'

Any help?

**Comment by GjjvdBurg** [comment]
Ah I see dataclasses was only added to the standard library starting with Python version 3.7. You can install a backport from PyPI though: ``pip install dataclasses``. Please let me know if that solves the issue

**Comment by GjjvdBurg** [comment]
fixed in v0.1.5
